# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Use the official Node.js 18 image
FROM node:18-alpine AS builder

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json into the container
COPY package.json package-lock.json ./

# Install dependencies (ignoring any scripts to avoid running "prepare" if it's set)
RUN npm install --ignore-scripts

# Copy the rest of the application's source code
COPY src ./src

# Build the application using TypeScript
RUN npm run build

# Use a lightweight Node.js image for the final build
FROM node:18-alpine AS production

# Set the working directory
WORKDIR /app

# Copy the built application from the builder stage
COPY --from=builder /app/build ./build
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json

# Install only production dependencies
RUN npm ci --production

# Set the environment variable for the CoinGecko API key
ENV COINGECKO_API_KEY=your_api_key_here

# Expose the necessary port (default is 3000, change if needed)
EXPOSE 3000

# Run the server
CMD ["node", "build/index.js"]